### ISSUE TITLE
Ubuntu 22.04 install - Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead

### ISSUE THREAD

**Issue by proddata** [crate/crate-tutorials#92] opened 2023-01-13 12:44 UTC
Need to update the Ubuntu install guide [^1], as currently there is a warning, that `apt-key` is deprecated.

```
root@test-ubuntu-install:~# apt-key add DEB-GPG-KEY-crate
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

---

might be useful: 
https://itsfoss.com/apt-key-deprecated/

[^1]: https://crate.io/docs/crate/tutorials/en/latest/basic/index.html#linux

**Comment by amotl** [comment] 2023-01-13 12:59
> Might be useful: https://itsfoss.com/apt-key-deprecated/

That's an extensive writeup, thanks for sharing!

> As you can see, there is no easy-to-use mechanism in place to replace the `apt-key` command. It requires a lot of manual effort and it should not be like this.

It's sad, right?

> In my opinion, the onus lies on the external repository provider. They should be the one providing the correct way of adding their repository. I see that [Brave browser provides the correct, modern instructions](https://brave.com/linux/) but many others, like Spotify, don’t do it.

Shall we update our instructions to align with the configuration style as provided by Brave? It looks like they are dropping a keyring file directly into `/usr/share/keyrings`, without using any other command at all. Edit: Oh ok, they directly provide key files in binary format, so that `gpg --dearmor` can be omitted.

**Comment by proddata** [comment] 2023-01-13 13:01
> Shall we update our instructions to align with the configuration style as provided by Brave?

I tried it quickly (the "proper way" and failed) 😢

**Comment by amotl** [comment] 2023-01-13 13:18
### Acquire the key - new style
Dropped the GPG key into `/usr/share/keyrings`.
```
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate | gpg --dearmor | tee /usr/share/keyrings/crateio.gpg
```

### Problem I
`add-apt-repository` does not understand the `signed-by` option?
```
add-apt-repository --yes "deb [signed-by=/usr/share/keyrings/crateio.gpg arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"
```
```
Unable to handle repository shortcut 'deb [signed-by=/usr/share/keyrings/crateio.gpg arch=amd64] https://cdn.crate.io/downloads/deb/stable/ jammy main'
```

### Problem II
When omitting that option, the configuration setting is accepted, but the key is not recognized.
```
add-apt-repository --yes "deb [arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"
```
```
Repository: 'deb [arch=amd64] https://cdn.crate.io/downloads/deb/stable/ jammy main'
Description:
Archive for codename: jammy components: main
More info: https://cdn.crate.io/downloads/deb/stable/
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_cdn_crate_io_downloads_deb_stable_-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_cdn_crate_io_downloads_deb_stable_-jammy.list
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:5 https://cdn.crate.io/downloads/deb/stable jammy InRelease [1844 B]
Err:5 https://cdn.crate.io/downloads/deb/stable jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FAAE51A06F6EAEB
Reading package lists... Done
W: GPG error: https://cdn.crate.io/downloads/deb/stable jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FAAE51A06F6EAEB
E: The repository 'https://cdn.crate.io/downloads/deb/stable jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by amotl** [comment] 2023-01-13 13:20
The file's types don't look too different.
```
file /usr/share/keyrings/ubuntu-archive-keyring.gpg
/usr/share/keyrings/ubuntu-archive-keyring.gpg: OpenPGP Public Key Version 4, Created Fri May 11 21:15:36 2012, RSA (Encrypt or Sign, 4096 bits); User ID; Signature; OpenPGP Certificate

file /usr/share/keyrings/crateio.gpg
/usr/share/keyrings/crateio.gpg:                OpenPGP Public Key Version 4, Created Tue Jan  7 09:38:40 2014, RSA (Encrypt or Sign, 4096 bits); User ID; Signature; OpenPGP Certificate
```

**Comment by amotl** [comment] 2023-01-13 13:27
> Warning: `apt-key` is deprecated. Manage keyring files in `trusted.gpg.d` instead.

The message is correct. Dropping the key into `/etc/apt/trusted.gpg.d` works, and solves _Problem II_.

```
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate | gpg --dearmor | tee /etc/apt/trusted.gpg.d/cratedb.gpg
```
```
add-apt-repository --yes "deb [arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"
```

**Comment by amotl** [comment] 2023-01-13 13:52
_Problem I_ can be solved by not using `add-apt-repository`, but just `echo` and `tee` instead.
```
echo "deb [signed-by=/etc/apt/trusted.gpg.d/cratedb.gpg arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main" | tee /etc/apt/sources.list.d/cratedb.list
```

**Comment by amotl** [comment] 2023-01-13 14:02
### Solution
```sh
docker run -it --rm ubuntu:22.04 bash
```
```sh
apt-get update
apt-get install --yes apt-transport-https apt-utils curl gnupg lsb-release
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate \
  | gpg --dearmor > /etc/apt/trusted.gpg.d/cratedb.gpg
[[ $(lsb_release --id --short) = "Ubuntu" ]] && repository="deb"
distribution=$(lsb_release --codename --short)
echo "deb [signed-by=/etc/apt/trusted.gpg.d/cratedb.gpg arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main" \
  > /etc/apt/sources.list.d/cratedb.list
apt-get update
apt show crate
```

### Outlook
The `lsb-release` package pulls in `python3`, so maybe the recipe can be optimized further, by using a different tool than `lsb_release`. However, @proddata says that `lsb-release` can usually be expected to be installed anyway.

**Comment by hlcianfagna** [comment] 2023-02-14 14:55
FWIW `add-apt-repository` works for me on Ubuntu Server 22.04.1 as follows:

```bash
sudo apt-get install curl gnupg software-properties-common apt-transport-https apt-utils
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate | sudo tee /etc/apt/trusted.gpg.d/crate.asc
repository="deb"
distribution=$(lsb_release --codename --short)
sudo add-apt-repository "deb [arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"
sudo apt update
sudo apt install crate
```

Note the `tee /etc/apt/trusted.gpg.d/crate.asc` bit (without `gpg --dearmor`) which is the only change from https://crate.io/docs/crate/tutorials/en/latest/basic/index.html#debian-or-ubuntu

**Comment by amotl** [comment] 2023-02-14 16:25
Thanks. I think the problem is that `add-apt-repository` can't handle the `signed-by=` parameter yet, which I think is recommended when adding third-party repositories these days.

Can you check if that would still work when using the not-dearmored key there?

**Comment by hlcianfagna** [comment] 2023-02-14 16:56
I see what you mean, indeed `add-apt-repository` does not take `signed-by`,
but this worked with the non-dearmored key for me:

```bash
curl -sS https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate | sudo tee /etc/apt/trusted.gpg.d/crate.asc
[[ $(lsb_release --id --short) = "Ubuntu" ]] && repository="deb"
distribution=$(lsb_release --codename --short)
echo "deb [signed-by=/etc/apt/trusted.gpg.d/crate.asc arch=amd64] https://cdn.crate.io/downloads/${repository}/stable/ ${distribution} main"  | sudo tee /etc/apt/sources.list.d/cratedb.list
sudo apt-get update
apt show crate
```

**Comment by amotl** [comment] 2023-02-14 17:16
Excellent. Thanks!

**Comment by amotl** [comment] 2023-02-20 13:49
Hi again. This will be resolved by GH-96, using the non-dearmored key directly, as @hlcianfagna suggested. Thanks!

**Comment by amotl** [comment] 2023-09-20 12:06
Hi. I guess this can be closed?

**Closed as completed** 2024-01-17 00:42 UTC
